# Whenever a tag push matching pattern "v*" then run the job
on: 
  push:
    tags:
      - "v*"

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Export Game
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.base_ref }}
    
    - name: setup java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - name: setup android sdk
      uses: android-actions/setup-android@v3.2.2
    
    - name: setup debug keystore
      run: |
        mkdir -p ~/.android
        keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
    
    - name: verify debug keystore
      run: keytool -list -v -keystore /home/runner/.android/debug.keystore -alias androiddebugkey -storepass android
    
    - name: copy editor settings
      run: |
        mkdir -p ~/.config/godot
        cp ${{ github.workspace }}/editor_settings-3.tres ~/.config/godot/
    

    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v6.0.0
      with:
        # Defining all the required inputs
        godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/3.6.1-stable/Godot_v3.6.1-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/3.6.1-stable/Godot_v3.6.1-stable_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        use_godot_3: true
        export_debug: true
    
      # This release action has worked well for me. However, you can most likely use any release action of your choosing.
      # https://github.com/ncipollo/release-action
    - name: create release
      uses: ncipollo/release-action@v1.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*